name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  branch-checks:
    name: Branch Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup and Install dependencies
        uses: ./.github/actions/setup
        env:
          TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}

      - name: Static Analysis
        uses: ./.github/actions/static-analysis

      - name: Build App
        uses: ./.github/actions/build-app
